export const cotizadorIsapresConfig = {
  sectionId: "cotizador-isapres",
  eyebrow: "Cotizador en línea",
  title: {
    prefix: "Encuentra tu",
    highlight: "plan de salud",
  },
  resultsSummary: {
    showing: 12,
    total: 435,
    subtitle: "Precios directos · Sin costo adicional",
  },
  regions: [
    "Región Metropolitana",
    "Región de Valparaíso",
    "Región del Biobío",
    "Región de La Araucanía",
    "Región de Los Lagos",
  ],
  genders: ["Femenino", "Masculino"],
  sortOptions: ["Menor precio", "Mayor cobertura", "Nombre A-Z"],
  isapreFilters: [
    { id: "consalud", label: "Consalud", checked: true, disabled: false },
    { id: "banmedica", label: "Banmédica", checked: false, disabled: false },
    { id: "colmena", label: "Colmena", checked: false, disabled: false },
    { id: "cruz-blanca", label: "Cruz Blanca", checked: false, disabled: false },
    { id: "mas", label: "y 4 más", checked: false, disabled: true },
  ],
  priceRange: {
    min: 44_867,
    max: 265_122,
  },
  plans: [
    {
      id: "13-core101-26",
      code: "13-CORE101-26",
      provider: "Consalud",
      tags: ["Base 1,160 UF", "Libre Elección"],
      priceUf: "1,160",
      priceClp: "$47.314",
      hospitalCoverage: 40,
      ambulatoryCoverage: 60,
      hospitals: ["Clínica RedSalud Santiago", "Clínica Indisa", "Clínica Dávila"],
      centers: ["Centro Médico RedSalud", "Clínica Alemana", "Megasalud"],
    },
    {
      id: "13-core102-26",
      code: "13-CORE102-26",
      provider: "Consalud",
      tags: ["Base 1,477 UF", "Libre Elección"],
      priceUf: "1,477",
      priceClp: "$60.248",
      hospitalCoverage: 45,
      ambulatoryCoverage: 65,
      hospitals: ["Clínica RedSalud Santiago", "Clínica Indisa", "Clínica Dávila"],
      centers: ["Centro Médico RedSalud", "Clínica Alemana", "Megasalud"],
    },
    {
      id: "13-core103-26",
      code: "13-CORE103-26",
      provider: "Consalud",
      tags: ["Base 1,542 UF", "Libre Elección"],
      priceUf: "1,542",
      priceClp: "$62.898",
      hospitalCoverage: 50,
      ambulatoryCoverage: 70,
      hospitals: ["Clínica RedSalud Santiago", "Clínica Indisa", "Clínica Dávila"],
      centers: ["Centro Médico RedSalud", "Clínica Alemana", "Megasalud"],
    },
    {
      id: "13-core104-26",
      code: "13-CORE104-26",
      provider: "Consalud",
      tags: ["Base 1,744 UF", "Libre Elección"],
      priceUf: "1,744",
      priceClp: "$71.141",
      hospitalCoverage: 55,
      ambulatoryCoverage: 75,
      hospitals: ["Clínica RedSalud Santiago", "Clínica Indisa", "Clínica Dávila"],
      centers: ["Centro Médico RedSalud", "Clínica Alemana", "Megasalud"],
    },
  ],
} as const;

export type CotizadorPlan = (typeof cotizadorIsapresConfig.plans)[number];
