import type { CotizadorPlan } from "@/types/cotizador-plan";

export const cotizadorIsapresConfig = {
  sectionId: "cotizador-isapres",
  eyebrow: "Cotizador en línea",
  title: {
    prefix: "Encuentra tu",
    highlight: "plan de salud",
  },
  resultsSummary: {
    showing: 12,
    total: 435,
    subtitle: "Precios directos · Sin costo adicional",
  },
  regions: [
    "Región Metropolitana",
    "Región de Arica y Parinacota",
    "Región de Tarapacá",
    "Región de Antofagasta",
    "Región de Atacama",
    "Región de Coquimbo",
    "Región de Valparaíso",
    "Región de O'Higgins",
    "Región del Maule",
    "Región de Ñuble",
    "Región del Biobío",
    "Región de La Araucanía",
    "Región de Los Ríos",
    "Región de Los Lagos",
    "Región de Aysén",
    "Región de Magallanes",
  ],
  genders: ["Femenino", "Masculino"],
  sortOptions: ["Menor precio", "Mayor cobertura", "Nombre A-Z"],
  isapreFilters: [
    { id: "consalud", label: "Consalud", checked: true, disabled: false },
    { id: "banmedica", label: "Banmédica", checked: true, disabled: false },
    { id: "colmena", label: "Colmena", checked: true, disabled: false },
    { id: "cruz-blanca", label: "Cruz Blanca", checked: true, disabled: false },
    { id: "mas", label: "y 4 más", checked: false, disabled: true },
  ],
  priceRange: {
    min: 44_867,
    max: 265_122,
  },
  plans: [
    {
      id: "13-core101-26",
      code: "13-CORE101-26",
      provider: "Consalud",
      planName: "CORE 101",
      tags: ["Base 1,160 UF", "Libre Elección"],
      priceUf: "1,160",
      priceClp: "$47.314",
      hospitalCoverage: 40,
      ambulatoryCoverage: 60,
      hospitalPercentages: [40, 50, 60],
      ambulatoryPercentages: [60, 70, 80],
      hospitals: [
        { name: "Clínica RedSalud Santiago", percentage: 40 },
        { name: "Clínica Indisa", percentage: 50 },
        { name: "Clínica Dávila", percentage: 60 },
      ],
      centers: [
        { name: "Centro Médico RedSalud", percentage: 60 },
        { name: "Clínica Alemana", percentage: 70 },
        { name: "Megasalud", percentage: 80 },
      ],
      hasTop: false,
      basePriceUf: 1.16,
    },
    {
      id: "13-core102-26",
      code: "13-CORE102-26",
      provider: "Consalud",
      planName: "CORE 102",
      tags: ["Base 1,477 UF", "Libre Elección"],
      priceUf: "1,477",
      priceClp: "$60.248",
      hospitalCoverage: 45,
      ambulatoryCoverage: 65,
      hospitalPercentages: [45, 55, 65],
      ambulatoryPercentages: [65, 75, 85],
      hospitals: [
        { name: "Clínica RedSalud Santiago", percentage: 45 },
        { name: "Clínica Indisa", percentage: 55 },
        { name: "Clínica Dávila", percentage: 65 },
      ],
      centers: [
        { name: "Centro Médico RedSalud", percentage: 65 },
        { name: "Clínica Alemana", percentage: 75 },
        { name: "Megasalud", percentage: 85 },
      ],
      hasTop: false,
      basePriceUf: 1.477,
    },
    {
      id: "13-core103-26",
      code: "13-CORE103-26",
      provider: "Consalud",
      planName: "CORE 103",
      tags: ["Base 1,542 UF", "Libre Elección"],
      priceUf: "1,542",
      priceClp: "$62.898",
      hospitalCoverage: 50,
      ambulatoryCoverage: 70,
      hospitalPercentages: [50, 60, 70],
      ambulatoryPercentages: [70, 80, 90],
      hospitals: [
        { name: "Clínica RedSalud Santiago", percentage: 50 },
        { name: "Clínica Indisa", percentage: 60 },
        { name: "Clínica Dávila", percentage: 70 },
      ],
      centers: [
        { name: "Centro Médico RedSalud", percentage: 70 },
        { name: "Clínica Alemana", percentage: 80 },
        { name: "Megasalud", percentage: 90 },
      ],
      hasTop: false,
      basePriceUf: 1.542,
    },
    {
      id: "13-core104-26",
      code: "13-CORE104-26",
      provider: "Consalud",
      planName: "CORE 104",
      tags: ["Base 1,744 UF", "Libre Elección"],
      priceUf: "1,744",
      priceClp: "$71.141",
      hospitalCoverage: 55,
      ambulatoryCoverage: 75,
      hospitalPercentages: [55, 65, 75],
      ambulatoryPercentages: [75, 85, 100],
      hospitals: [
        { name: "Clínica RedSalud Santiago", percentage: 55 },
        { name: "Clínica Indisa", percentage: 65 },
        { name: "Clínica Dávila", percentage: 75 },
      ],
      centers: [
        { name: "Centro Médico RedSalud", percentage: 75 },
        { name: "Clínica Alemana", percentage: 85 },
        { name: "Megasalud", percentage: 100 },
      ],
      hasTop: false,
      basePriceUf: 1.744,
    },
  ] satisfies CotizadorPlan[],
} as const;

export type { CotizadorPlan };
