export const siteConfig = {
  name: "Cotízalo Antes",
  tagline: "Compara Isapres, AFP y Seguros en Chile",
  description:
    "Cotízalo Antes es el comparador y cotizador líder de Isapres, AFP y seguros en Chile. Compara planes de salud, cotiza online gratis y elige la mejor opción para ti y tu familia.",
  url: "https://cotizaloantes.cl",
  cotizadorIsapresUrl: "https://cotizador.cotizaloantes.cl/",
  ogImage: "/opengraph-image",
  logo: {
    src: "/images/logo-cotizalo-antes.png",
    alt: "Cotízalo Antes — Comparador de Isapres, AFP y Seguros en Chile",
    width: 320,
    height: 80,
  },
  locale: "es_CL",
  language: "es-CL",
  country: "Chile",
  contact: {
    phone: "+56930102427",
    email: "contacto@cotizaloantes.cl",
  },
  keywords: [
    "cotizador isapre",
    "comparador isapre chile",
    "comparar isapres",
    "planes de salud chile",
    "cotizador afp",
    "comparador afp chile",
    "cotizador seguros chile",
    "isapre colmena",
    "isapre banmédica",
    "isapre consalud",
    "cotizar plan de salud",
    "mejor isapre chile",
    "comparabien isapre",
    "plan de salud chile",
    "cotizalo antes",
  ],
} as const;
